SELECT ORDER_ID, o.PRODUCT_ID, pi.PRODUCT_ID as ProductNotPurchased, 
PRODUCT_NAME
FROM ORDERS o, PRODUCT_INFORMATION pi
WHERE o.product_id = pi.product_id
	AND o.PRODUCT_ID IS NULL
	AND pi.PRODUCT_ID IS NOT NULL;
