SPOOL ps15_output.sql REPLACE
CLEAR COLUMNS
CLEAR BREAKS
CLEAR COMPUTES
SET PAGESIZE 100
SET FEEDBACK OFF
SET VERIFY OFF
SET HEADING OFF
TTITLE CENTER 'Summary Report For New Customers'
@ps15c.sql

SPOOL OFF
